{% set name = "versioningit" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7aac713c31a53eb367a6bbc2e8b3de8cc2b86d10d45c5101afd651446cb10fd7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - versioningit = versioningit.__main__:main

requirements:
  host:
    - hatchling
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - importlib-metadata >=3.6
    - packaging >=17.1
    - tomli >=1.2,<3.0

test:
  requires:
    - python-build >=0.7.0
    - git >=2.32
    - hatchling
    - mercurial >=5.2
    - setuptools >=42
    - pip
    - pydantic >=2.0,<3.0
    - pytest >=7.0
    - pytest-cov >=3.0
    - pytest-mock >=3.0
    - wheel
  source_files:
    - test
    - tox.ini
  imports:
    - versioningit
  commands:
    - pip check
    - versioningit --help
    - python -m pytest -vv test

about:
  home: https://github.com/jwodder/versioningit
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Versioning It with your Version In Git
  description: |
    `versioningit` is yet another Python packaging plugin for automatically
    determining your package's version based on your version control
    repository's tags.  Unlike others, it allows easy customization of the
    version format and even lets you easily override the separate functions
    used for version extraction & calculation.
  dev_url: https://github.com/jwodder/versioningit

extra:
  recipe-maintainers:
    - jwodder
