{% set name = "versioningit" %}
{% set version = "3.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4db83ed99f56b07d83940bee3445ca46ca120d13b6b304cdb5fb44e5aa4edec0

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - versioningit = versioningit.__main__:main

requirements:
  host:
    - hatchling
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - importlib-metadata >=3.6
    - packaging >=17.1
    - tomli >=1.2,<3.0

test:
  requires:
    - python-build >=0.7.0
    - editables
    - git >=2.32
    - hatchling
    - mercurial >=5.2
    - setuptools >=42
    - pip
    - pydantic >=2.0,<3.0
    - pytest >=7.0
    - pytest-cov >=3.0
    - pytest-mock >=3.0
    - wheel
    - python {{ python_min }}
  source_files:
    - test
    - tox.ini
  imports:
    - versioningit
  commands:
    - pip check
    - versioningit --help
    - python -m pytest -vv test

about:
  home: https://github.com/jwodder/versioningit
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Versioning It with your Version In Git
  description: |
    `versioningit` is yet another Python packaging plugin for automatically
    determining your package's version based on your version control
    repository's tags.  Unlike others, it allows easy customization of the
    version format and even lets you easily override the separate functions
    used for version extraction & calculation.
  dev_url: https://github.com/jwodder/versioningit

extra:
  recipe-maintainers:
    - jwodder
